// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PcBuilder.Data;
using PcBuilder.Enums;

#nullable disable

namespace PcBuilder.Migrations
{
    [DbContext(typeof(PcDbContext))]
    [Migration("20260430103528_ChangePgNameForSocketField")]
    partial class ChangePgNameForSocketField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "cooler_type", new[] { "AIO Liquid", "Air", "Custom Liquid" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "form_factor", new[] { "ATX", "E-ATX", "Micro-ATX", "Mini-ITX", "SSI-CEB", "XL-ATX" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "gpu_interface", new[] { "PCIe 3.0 x16", "PCIe 4.0 x16", "PCIe 5.0 x16" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "memory_type", new[] { "DDR4", "DDR4/DDR5", "DDR5" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "panel_type", new[] { "IPS", "Mini-LED", "OLED", "QD-OLED", "TN", "VA" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "psu_modular", new[] { "Fully Modular", "Non-Modular", "Semi-Modular" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "psu_rating", new[] { "80+ Bronze", "80+ Gold", "80+ Platinum", "80+ Silver", "80+ Titanium", "80+ White" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "socket_type", new[] { "AM4", "AM5", "LGA1200", "LGA1700", "LGA1851", "LGA2066", "SP3", "sTR4", "sTRX4" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "storage_form_factor", new[] { "2.5", "3.5", "Add-In Card", "M.2 22110", "M.2 2242", "M.2 2260", "M.2 2280", "U.2" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "storage_interface", new[] { "NVMe PCIe 3.0", "NVMe PCIe 4.0", "NVMe PCIe 5.0", "SAS", "SATA III" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PcBuilder.Models.Admin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("userId")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("PcBuilder.Models.Brand", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Brand", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PcBuilder.Models.Build", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("caseId")
                        .HasColumnType("integer");

                    b.Property<int?>("cpuCoolerId")
                        .HasColumnType("integer");

                    b.Property<int?>("cpuId")
                        .HasColumnType("integer");

                    b.Property<int?>("gpuId")
                        .HasColumnType("integer");

                    b.Property<int?>("hardDriveId")
                        .HasColumnType("integer");

                    b.Property<int?>("monitorId")
                        .HasColumnType("integer");

                    b.Property<int?>("motherboardId")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<int?>("psuId")
                        .HasColumnType("integer");

                    b.Property<int?>("ramId")
                        .HasColumnType("integer");

                    b.Property<string>("userId")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("caseId");

                    b.HasIndex("cpuCoolerId");

                    b.HasIndex("cpuId");

                    b.HasIndex("gpuId");

                    b.HasIndex("hardDriveId");

                    b.HasIndex("monitorId");

                    b.HasIndex("motherboardId");

                    b.HasIndex("psuId");

                    b.HasIndex("ramId");

                    b.HasIndex("userId");

                    b.ToTable("Build");
                });

            modelBuilder.Entity("PcBuilder.Models.Cpu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<double>("baseClockGhz")
                        .HasColumnType("double precision")
                        .HasColumnName("base_clock_ghz");

                    b.Property<double?>("boostClockGhz")
                        .HasColumnType("double precision")
                        .HasColumnName("boost_clock_ghz");

                    b.Property<int>("brandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.PrimitiveCollection<List<string>>("chipsetsSupported")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("chipsets_supported");

                    b.Property<int>("cores")
                        .HasColumnType("integer")
                        .HasColumnName("cores");

                    b.Property<string>("igpuModel")
                        .HasColumnType("text")
                        .HasColumnName("igpu_model");

                    b.Property<bool>("includesCooler")
                        .HasColumnType("boolean")
                        .HasColumnName("includes_cooler");

                    b.Property<bool>("integratedGraphics")
                        .HasColumnType("boolean")
                        .HasColumnName("integrated_graphics");

                    b.Property<int?>("l3CacheMb")
                        .HasColumnType("integer")
                        .HasColumnName("l3_cache_mb");

                    b.Property<int?>("launchedYear")
                        .HasColumnType("integer")
                        .HasColumnName("launched_year");

                    b.Property<int>("maxMemoryGb")
                        .HasColumnType("integer")
                        .HasColumnName("max_memory_gb");

                    b.Property<int>("maxMemorySpeedMhz")
                        .HasColumnType("integer")
                        .HasColumnName("max_memory_speed_mhz");

                    b.Property<int>("memoryChannels")
                        .HasColumnType("integer")
                        .HasColumnName("memory_channels");

                    b.Property<MemoryType>("memoryType")
                        .HasColumnType("memory_type")
                        .HasColumnName("memory_type");

                    b.Property<string>("modelNumber")
                        .HasColumnType("text")
                        .HasColumnName("model_number");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("pcieLanes")
                        .HasColumnType("integer")
                        .HasColumnName("pcie_lanes");

                    b.Property<string>("pcieVersion")
                        .HasColumnType("text")
                        .HasColumnName("pcie_version");

                    b.Property<decimal?>("priceUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd");

                    b.Property<PcSocketType>("socket")
                        .HasColumnType("socket_type")
                        .HasColumnName("socket");

                    b.Property<int>("tdpWatts")
                        .HasColumnType("integer")
                        .HasColumnName("tdp_watts");

                    b.Property<int>("threads")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("brandId");

                    b.ToTable("Cpu", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PcBuilder.Models.CpuCooler", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("brandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<CoolerType>("coolerType")
                        .HasColumnType("cooler_type")
                        .HasColumnName("cooler_type");

                    b.Property<int>("fanCount")
                        .HasColumnType("integer")
                        .HasColumnName("fan_count");

                    b.Property<int>("fanSizeMm")
                        .HasColumnType("integer")
                        .HasColumnName("fan_size_mm");

                    b.Property<bool>("hasRgb")
                        .HasColumnType("boolean")
                        .HasColumnName("has_rgb");

                    b.Property<int?>("heightMm")
                        .HasColumnType("integer")
                        .HasColumnName("height_mm");

                    b.Property<int>("maxTdpWatts")
                        .HasColumnType("integer")
                        .HasColumnName("max_tdp_watts");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double?>("noiseLevelDb")
                        .HasColumnType("double precision")
                        .HasColumnName("noise_db");

                    b.Property<decimal?>("priceUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd");

                    b.Property<int?>("radiatorSizeMm")
                        .HasColumnType("integer")
                        .HasColumnName("radiator_size_mm");

                    b.PrimitiveCollection<string[]>("socketsSupported")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("sockets_supported");

                    b.HasKey("id");

                    b.HasIndex("brandId");

                    b.ToTable("CpuCooler", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PcBuilder.Models.Gpu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("baseClockMhz")
                        .HasColumnType("integer")
                        .HasColumnName("base_clock_mhz");

                    b.Property<int>("boostClockMhz")
                        .HasColumnType("integer")
                        .HasColumnName("boost_clock_mhz");

                    b.Property<int>("brandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<int?>("cardLengthMm")
                        .HasColumnType("integer")
                        .HasColumnName("card_length_mm");

                    b.Property<double>("cordSlots")
                        .HasColumnType("double precision")
                        .HasColumnName("cord_slots");

                    b.Property<string>("gpuChip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grpu_chip");

                    b.Property<GpuInterface>("gpuInterface")
                        .HasColumnType("gpu_interface")
                        .HasColumnName("interface");

                    b.Property<bool>("hasRgb")
                        .HasColumnType("boolean")
                        .HasColumnName("has_rgb");

                    b.Property<double?>("memoryBandwithGb")
                        .HasColumnType("double precision")
                        .HasColumnName("memory_bandwidth_gb");

                    b.Property<int>("memoryBusBits")
                        .HasColumnType("integer")
                        .HasColumnName("memory_bus_bits");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("outputDp")
                        .HasColumnType("integer")
                        .HasColumnName("output_dp");

                    b.Property<int>("outputHdmi")
                        .HasColumnType("integer")
                        .HasColumnName("output_hdmi");

                    b.Property<string>("powerConnectors")
                        .HasColumnType("text")
                        .HasColumnName("power_connectors");

                    b.Property<decimal?>("price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("recommendedPsuWattage")
                        .HasColumnType("integer")
                        .HasColumnName("recommended_psu_wattage");

                    b.Property<int>("tdpWatts")
                        .HasColumnType("integer")
                        .HasColumnName("tdp_watts");

                    b.Property<string>("vramType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vram_type");

                    b.Property<int>("vram_gb")
                        .HasColumnType("integer")
                        .HasColumnName("vram_gb");

                    b.HasKey("id");

                    b.HasIndex("brandId");

                    b.ToTable("Gpu", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PcBuilder.Models.HardDrive", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("brandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<int?>("cacheMb")
                        .HasColumnType("integer")
                        .HasColumnName("cache_mb");

                    b.Property<int>("capacityGb")
                        .HasColumnType("integer")
                        .HasColumnName("capacity_gb");

                    b.Property<StorageInterface>("driveInterface")
                        .HasColumnType("storage_interface")
                        .HasColumnName("interface");

                    b.Property<StorageFormFactor>("formFactor")
                        .HasColumnType("storage_form_factor")
                        .HasColumnName("form_factor");

                    b.Property<bool>("isSsd")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ssd");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double?>("powerWatts")
                        .HasColumnType("double precision")
                        .HasColumnName("power_watts");

                    b.Property<decimal?>("priceUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd");

                    b.Property<int?>("readSpeedMbS")
                        .HasColumnType("integer")
                        .HasColumnName("read_speed_mbps");

                    b.Property<int?>("rpm")
                        .HasColumnType("integer");

                    b.Property<int?>("tbw")
                        .HasColumnType("integer");

                    b.Property<int?>("writeSpeedMbs")
                        .HasColumnType("integer")
                        .HasColumnName("write_speed_mbps");

                    b.HasKey("id");

                    b.HasIndex("brandId");

                    b.ToTable("HardDrive", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PcBuilder.Models.Motherboard", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("argbHeaders")
                        .HasColumnType("integer")
                        .HasColumnName("argb_headers");

                    b.Property<int>("brandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<string>("chipset")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chipset");

                    b.Property<int>("fanHeaders")
                        .HasColumnType("integer")
                        .HasColumnName("fan_headers");

                    b.Property<FormFactor>("formFactor")
                        .HasColumnType("form_factor")
                        .HasColumnName("form_factor");

                    b.Property<bool>("hasBluetooth")
                        .HasColumnType("boolean")
                        .HasColumnName("has_bluetooth");

                    b.Property<bool>("hasWifi")
                        .HasColumnType("boolean")
                        .HasColumnName("has_wifi");

                    b.Property<int>("lanSpeedGbps")
                        .HasColumnType("integer")
                        .HasColumnName("lan_speed_gbps");

                    b.Property<int>("m2Slots")
                        .HasColumnType("integer")
                        .HasColumnName("m2_slots");

                    b.Property<int>("maxMemoryGb")
                        .HasColumnType("integer")
                        .HasColumnName("max_memory_gb");

                    b.Property<int>("maxMemorySpeedMhz")
                        .HasColumnType("integer")
                        .HasColumnName("max_memory_speed_mhz");

                    b.Property<int>("memorySlots")
                        .HasColumnType("integer")
                        .HasColumnName("memory_slots");

                    b.Property<MemoryType>("memoryType")
                        .HasColumnType("memory_type")
                        .HasColumnName("memory_type");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("pcieX16Slots")
                        .HasColumnType("integer")
                        .HasColumnName("pcie_x16_slots");

                    b.Property<int>("pcieX1Slots")
                        .HasColumnType("integer")
                        .HasColumnName("pcie_x1_slots");

                    b.Property<decimal?>("priceUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd");

                    b.Property<int>("rearDisplayPort")
                        .HasColumnType("integer")
                        .HasColumnName("rear_display_port");

                    b.Property<int>("rearHdmi")
                        .HasColumnType("integer")
                        .HasColumnName("rear_hdmi");

                    b.Property<int>("rearUsbA")
                        .HasColumnType("integer")
                        .HasColumnName("rear_usb_a");

                    b.Property<int>("rearUsbC")
                        .HasColumnType("integer")
                        .HasColumnName("rear_usb_c");

                    b.Property<int>("sataPorts")
                        .HasColumnType("integer")
                        .HasColumnName("sata_ports");

                    b.Property<PcSocketType>("socket")
                        .HasColumnType("socket_type")
                        .HasColumnName("socket");

                    b.Property<int>("usbHeaders2Gen0")
                        .HasColumnType("integer")
                        .HasColumnName("usb_headers_2_0");

                    b.Property<int>("usbHeaders3Gen2")
                        .HasColumnType("integer")
                        .HasColumnName("usb_headers_3_2");

                    b.Property<int?>("vrmPhases")
                        .HasColumnType("integer")
                        .HasColumnName("vrm_phases");

                    b.HasKey("id");

                    b.HasIndex("brandId");

                    b.ToTable("Motherboard", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PcBuilder.Models.PcCase", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("brandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<int?>("caseDepthMm")
                        .HasColumnType("integer")
                        .HasColumnName("case_depth_mm");

                    b.Property<int?>("caseHeightMm")
                        .HasColumnType("integer")
                        .HasColumnName("case_height_mm");

                    b.Property<int?>("caseWidthMm")
                        .HasColumnType("integer")
                        .HasColumnName("case_width_mm");

                    b.Property<int>("driveBays25Inch")
                        .HasColumnType("integer")
                        .HasColumnName("drive_bays_25");

                    b.Property<int>("driveBays35Inch")
                        .HasColumnType("integer")
                        .HasColumnName("drive_bays_35");

                    b.Property<int>("frontUsbA")
                        .HasColumnType("integer")
                        .HasColumnName("front_usb_a");

                    b.Property<int>("frontUsbC")
                        .HasColumnType("integer")
                        .HasColumnName("front_usb_c");

                    b.Property<bool>("hasGlassPanel")
                        .HasColumnType("boolean")
                        .HasColumnName("has_glass_panel");

                    b.Property<int>("includedFans")
                        .HasColumnType("integer")
                        .HasColumnName("included_fans");

                    b.Property<int>("maxCpuCoolerHeightMm")
                        .HasColumnType("integer")
                        .HasColumnName("max_cpu_cooler_height_mm");

                    b.Property<int>("maxGpuLengthMm")
                        .HasColumnType("integer")
                        .HasColumnName("max_gpu_length_mm");

                    b.Property<int>("maxPsuLengthMm")
                        .HasColumnType("integer")
                        .HasColumnName("max_psu_length_mm");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("priceUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd");

                    b.PrimitiveCollection<List<string>>("radiatorSupportMm")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("radiator_support_mm");

                    b.PrimitiveCollection<List<string>>("supportedFormFactors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("form_factors_supported");

                    b.HasKey("id");

                    b.HasIndex("brandId");

                    b.ToTable("PcCase", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PcBuilder.Models.PcMonitor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("brandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<int?>("brightnessNits")
                        .HasColumnType("integer")
                        .HasColumnName("brightness_nits");

                    b.Property<int?>("colorGamutP3")
                        .HasColumnType("integer")
                        .HasColumnName("color_gamut_p3");

                    b.Property<string>("contrastRatio")
                        .HasColumnType("text")
                        .HasColumnName("contrast_ratio");

                    b.Property<int>("dpPorts")
                        .HasColumnType("integer")
                        .HasColumnName("inputs_dp");

                    b.Property<string>("dpVersion")
                        .HasColumnType("text")
                        .HasColumnName("dp_version");

                    b.Property<bool>("hasFreeSync")
                        .HasColumnType("boolean")
                        .HasColumnName("has_freesync");

                    b.Property<bool>("hasFreeSyncPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("has_freesync_premium");

                    b.Property<bool>("hasGSync")
                        .HasColumnType("boolean")
                        .HasColumnName("has_gsync");

                    b.Property<bool>("hasSpeakers")
                        .HasColumnType("boolean")
                        .HasColumnName("has_speakers");

                    b.Property<bool>("hasUsbHub")
                        .HasColumnType("boolean")
                        .HasColumnName("has_usb_hub");

                    b.Property<int>("hdmiPorts")
                        .HasColumnType("integer")
                        .HasColumnName("inputs_hdmi");

                    b.Property<string>("hdmiVersion")
                        .HasColumnType("text")
                        .HasColumnName("hdmi_version");

                    b.Property<string>("hdrSupport")
                        .HasColumnType("text")
                        .HasColumnName("hdr_support");

                    b.Property<bool>("heightAdjustable")
                        .HasColumnType("boolean")
                        .HasColumnName("height_adjustable");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<PanelType>("panelType")
                        .HasColumnType("panel_type")
                        .HasColumnName("panel_type");

                    b.Property<decimal?>("priceUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd");

                    b.Property<int>("refreshRateHz")
                        .HasColumnType("integer")
                        .HasColumnName("refresh_rate_hz");

                    b.Property<int>("resolutionHeight")
                        .HasColumnType("integer")
                        .HasColumnName("resolution_height");

                    b.Property<int>("resolutionWidth")
                        .HasColumnType("integer")
                        .HasColumnName("resolution_width");

                    b.Property<double?>("responseTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("response_time_ms");

                    b.Property<double>("screenSizeInch")
                        .HasColumnType("double precision")
                        .HasColumnName("screen_size_inch");

                    b.Property<int>("usbCPorts")
                        .HasColumnType("integer")
                        .HasColumnName("inputs_usb_c");

                    b.Property<string>("vesaMount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vesa_mount");

                    b.HasKey("id");

                    b.HasIndex("brandId");

                    b.ToTable("PcMonitor", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PcBuilder.Models.Psu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("atxVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("atx_version");

                    b.Property<int>("brandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<PsuRating>("efficiency")
                        .HasColumnType("psu_rating")
                        .HasColumnName("efficiency");

                    b.Property<int>("epsConnectors")
                        .HasColumnType("integer")
                        .HasColumnName("eps_connectors");

                    b.Property<int>("fanSizeMm")
                        .HasColumnType("integer")
                        .HasColumnName("fan_size_mm");

                    b.Property<bool>("has16Pin")
                        .HasColumnType("boolean")
                        .HasColumnName("has_16pin");

                    b.Property<int?>("lengthMm")
                        .HasColumnType("integer")
                        .HasColumnName("length_mm");

                    b.Property<PsuModular>("modularity")
                        .HasColumnType("psu_modular")
                        .HasColumnName("modularity");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("pcie8PinConnectors")
                        .HasColumnType("integer")
                        .HasColumnName("pcie_8pin");

                    b.Property<decimal?>("priceUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd");

                    b.Property<int>("sataConnectors")
                        .HasColumnType("integer")
                        .HasColumnName("sata_connectors");

                    b.Property<int>("wattage")
                        .HasColumnType("integer")
                        .HasColumnName("wattage");

                    b.HasKey("id");

                    b.HasIndex("brandId");

                    b.ToTable("Psu", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PcBuilder.Models.Ram", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("brandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<int>("capacityGb")
                        .HasColumnType("integer")
                        .HasColumnName("capacity_gb");

                    b.Property<int?>("casLatency")
                        .HasColumnType("integer")
                        .HasColumnName("cas_latency");

                    b.Property<bool>("hasEcc")
                        .HasColumnType("boolean")
                        .HasColumnName("has_ecc");

                    b.Property<bool>("hasRgb")
                        .HasColumnType("boolean")
                        .HasColumnName("has_rgb");

                    b.Property<int?>("heightMm")
                        .HasColumnType("integer")
                        .HasColumnName("height_mm");

                    b.Property<int>("kitCount")
                        .HasColumnType("integer")
                        .HasColumnName("kit_count");

                    b.Property<MemoryType>("memoryType")
                        .HasColumnType("memory_type")
                        .HasColumnName("memory_type");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("priceUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd");

                    b.Property<int>("speedMhz")
                        .HasColumnType("integer")
                        .HasColumnName("speed_mhz");

                    b.Property<double?>("voltage")
                        .HasColumnType("double precision")
                        .HasColumnName("voltage");

                    b.HasKey("id");

                    b.HasIndex("brandId");

                    b.ToTable("Ram", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PcBuilder.Models.RegularUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("buildsCreated")
                        .HasColumnType("integer");

                    b.Property<string>("postalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("prefferedCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("RegularUser");
                });

            modelBuilder.Entity("PcBuilder.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PcBuilder.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PcBuilder.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PcBuilder.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PcBuilder.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilder.Models.Admin", b =>
                {
                    b.HasOne("PcBuilder.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId");

                    b.Navigation("user");
                });

            modelBuilder.Entity("PcBuilder.Models.Build", b =>
                {
                    b.HasOne("PcBuilder.Models.PcCase", "pcCase")
                        .WithMany()
                        .HasForeignKey("caseId");

                    b.HasOne("PcBuilder.Models.CpuCooler", "cpuCooler")
                        .WithMany()
                        .HasForeignKey("cpuCoolerId");

                    b.HasOne("PcBuilder.Models.Cpu", "cpu")
                        .WithMany()
                        .HasForeignKey("cpuId");

                    b.HasOne("PcBuilder.Models.Gpu", "gpu")
                        .WithMany()
                        .HasForeignKey("gpuId");

                    b.HasOne("PcBuilder.Models.HardDrive", "hardDrive")
                        .WithMany()
                        .HasForeignKey("hardDriveId");

                    b.HasOne("PcBuilder.Models.PcMonitor", "monitor")
                        .WithMany()
                        .HasForeignKey("monitorId");

                    b.HasOne("PcBuilder.Models.Motherboard", "motherboard")
                        .WithMany()
                        .HasForeignKey("motherboardId");

                    b.HasOne("PcBuilder.Models.Psu", "psu")
                        .WithMany()
                        .HasForeignKey("psuId");

                    b.HasOne("PcBuilder.Models.Ram", "ram")
                        .WithMany()
                        .HasForeignKey("ramId");

                    b.HasOne("PcBuilder.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("cpu");

                    b.Navigation("cpuCooler");

                    b.Navigation("gpu");

                    b.Navigation("hardDrive");

                    b.Navigation("monitor");

                    b.Navigation("motherboard");

                    b.Navigation("pcCase");

                    b.Navigation("psu");

                    b.Navigation("ram");

                    b.Navigation("user");
                });

            modelBuilder.Entity("PcBuilder.Models.Cpu", b =>
                {
                    b.HasOne("PcBuilder.Models.Brand", "brand")
                        .WithMany()
                        .HasForeignKey("brandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("brand");
                });

            modelBuilder.Entity("PcBuilder.Models.CpuCooler", b =>
                {
                    b.HasOne("PcBuilder.Models.Brand", "brand")
                        .WithMany()
                        .HasForeignKey("brandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("brand");
                });

            modelBuilder.Entity("PcBuilder.Models.Gpu", b =>
                {
                    b.HasOne("PcBuilder.Models.Brand", "brand")
                        .WithMany()
                        .HasForeignKey("brandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("brand");
                });

            modelBuilder.Entity("PcBuilder.Models.HardDrive", b =>
                {
                    b.HasOne("PcBuilder.Models.Brand", "brand")
                        .WithMany()
                        .HasForeignKey("brandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("brand");
                });

            modelBuilder.Entity("PcBuilder.Models.Motherboard", b =>
                {
                    b.HasOne("PcBuilder.Models.Brand", "brand")
                        .WithMany()
                        .HasForeignKey("brandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("brand");
                });

            modelBuilder.Entity("PcBuilder.Models.PcCase", b =>
                {
                    b.HasOne("PcBuilder.Models.Brand", "brand")
                        .WithMany()
                        .HasForeignKey("brandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("brand");
                });

            modelBuilder.Entity("PcBuilder.Models.PcMonitor", b =>
                {
                    b.HasOne("PcBuilder.Models.Brand", "brand")
                        .WithMany()
                        .HasForeignKey("brandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("brand");
                });

            modelBuilder.Entity("PcBuilder.Models.Psu", b =>
                {
                    b.HasOne("PcBuilder.Models.Brand", "brand")
                        .WithMany()
                        .HasForeignKey("brandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("brand");
                });

            modelBuilder.Entity("PcBuilder.Models.Ram", b =>
                {
                    b.HasOne("PcBuilder.Models.Brand", "brand")
                        .WithMany()
                        .HasForeignKey("brandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("brand");
                });

            modelBuilder.Entity("PcBuilder.Models.RegularUser", b =>
                {
                    b.HasOne("PcBuilder.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
