// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PcBuilder.Data;

#nullable disable

namespace PcBuilder.Migrations;

[DbContext(typeof(PcDbContext))]
[Migration("20260416120840_Init")]
partial class Init
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.6")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("RoleNameIndex");

                b.ToTable("AspNetRoles", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .HasColumnType("text");

                b.Property<string>("ClaimValue")
                    .HasColumnType("text");

                b.Property<string>("RoleId")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.ToTable("AspNetRoleClaims", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("text");

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("integer");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("text");

                b.Property<string>("Discriminator")
                    .IsRequired()
                    .HasMaxLength(13)
                    .HasColumnType("character varying(13)");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("boolean");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("boolean");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("PasswordHash")
                    .HasColumnType("text");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("text");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("boolean");

                b.Property<string>("SecurityStamp")
                    .HasColumnType("text");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("boolean");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.HasKey("Id");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("EmailIndex");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("UserNameIndex");

                b.ToTable("AspNetUsers", (string)null);

                b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                b.UseTphMappingStrategy();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .HasColumnType("text");

                b.Property<string>("ClaimValue")
                    .HasColumnType("text");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserClaims", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasColumnType("text");

                b.Property<string>("ProviderKey")
                    .HasColumnType("text");

                b.Property<string>("ProviderDisplayName")
                    .HasColumnType("text");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("LoginProvider", "ProviderKey");

                b.HasIndex("UserId");

                b.ToTable("AspNetUserLogins", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("text");

                b.Property<string>("RoleId")
                    .HasColumnType("text");

                b.HasKey("UserId", "RoleId");

                b.HasIndex("RoleId");

                b.ToTable("AspNetUserRoles", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.Property<string>("UserId")
                    .HasColumnType("text");

                b.Property<string>("LoginProvider")
                    .HasColumnType("text");

                b.Property<string>("Name")
                    .HasColumnType("text");

                b.Property<string>("Value")
                    .HasColumnType("text");

                b.HasKey("UserId", "LoginProvider", "Name");

                b.ToTable("AspNetUserTokens", (string)null);
            });

        modelBuilder.Entity("PcBuilder.Models.Admin", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                b.Property<string>("userId")
                    .HasColumnType("text");

                b.HasKey("id");

                b.HasIndex("userId");

                b.ToTable("admin");
            });

        modelBuilder.Entity("PcBuilder.Models.Brand", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("brand", null, t =>
                    {
                        t.ExcludeFromMigrations();
                    });
            });

        modelBuilder.Entity("PcBuilder.Models.Build", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                b.Property<int?>("caseId")
                    .HasColumnType("integer");

                b.Property<int?>("cpuCoolerId")
                    .HasColumnType("integer");

                b.Property<int?>("cpuId")
                    .HasColumnType("integer");

                b.Property<int?>("gpuId")
                    .HasColumnType("integer");

                b.Property<int?>("hardDriveId")
                    .HasColumnType("integer");

                b.Property<int?>("monitorId")
                    .HasColumnType("integer");

                b.Property<int?>("motherboardId")
                    .HasColumnType("integer");

                b.Property<string>("name")
                    .HasColumnType("text");

                b.Property<int?>("psuId")
                    .HasColumnType("integer");

                b.Property<int?>("ramId")
                    .HasColumnType("integer");

                b.Property<string>("userId")
                    .HasColumnType("text");

                b.HasKey("id");

                b.HasIndex("caseId");

                b.HasIndex("cpuCoolerId");

                b.HasIndex("cpuId");

                b.HasIndex("gpuId");

                b.HasIndex("hardDriveId");

                b.HasIndex("monitorId");

                b.HasIndex("motherboardId");

                b.HasIndex("psuId");

                b.HasIndex("ramId");

                b.HasIndex("userId");

                b.ToTable("build");
            });

        modelBuilder.Entity("PcBuilder.Models.Case", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                b.Property<int>("brandId")
                    .HasColumnType("integer");

                b.Property<int?>("caseDepthMm")
                    .HasColumnType("integer");

                b.Property<int?>("caseHeightMm")
                    .HasColumnType("integer");

                b.Property<int?>("caseWidthMm")
                    .HasColumnType("integer");

                b.Property<int>("driveBays25Inch")
                    .HasColumnType("integer");

                b.Property<int>("driveBays35Inch")
                    .HasColumnType("integer");

                b.Property<int>("frontUsbA")
                    .HasColumnType("integer");

                b.Property<int>("frontUsbC")
                    .HasColumnType("integer");

                b.Property<bool>("hasGlassPanel")
                    .HasColumnType("boolean");

                b.Property<int>("includedFans")
                    .HasColumnType("integer");

                b.Property<int>("maxCpuCoolerHeightMm")
                    .HasColumnType("integer");

                b.Property<int>("maxGpuLengthMm")
                    .HasColumnType("integer");

                b.Property<int>("maxPsuLengthMm")
                    .HasColumnType("integer");

                b.Property<string>("name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<decimal?>("priceUsd")
                    .HasColumnType("numeric");

                b.PrimitiveCollection<string[]>("radiatorSupportMm")
                    .HasColumnType("text[]");

                b.PrimitiveCollection<string[]>("supportedFormFactors")
                    .IsRequired()
                    .HasColumnType("text[]");

                b.HasKey("id");

                b.HasIndex("brandId");

                b.ToTable("pc_case", null, t =>
                    {
                        t.ExcludeFromMigrations();
                    });
            });

        modelBuilder.Entity("PcBuilder.Models.Cpu", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                b.Property<double>("baseClockGhz")
                    .HasColumnType("double precision");

                b.Property<double?>("boostClockGhz")
                    .HasColumnType("double precision");

                b.Property<int>("brandId")
                    .HasColumnType("integer");

                b.PrimitiveCollection<string[]>("chipsetsSupported")
                    .IsRequired()
                    .HasColumnType("text[]");

                b.Property<int>("cores")
                    .HasColumnType("integer");

                b.Property<string>("igpuModel")
                    .HasColumnType("text");

                b.Property<bool>("includesCooler")
                    .HasColumnType("boolean");

                b.Property<bool>("integratedGraphics")
                    .HasColumnType("boolean");

                b.Property<int?>("l3CacheMb")
                    .HasColumnType("integer");

                b.Property<int?>("launchedYear")
                    .HasColumnType("integer");

                b.Property<int>("maxMemoryGb")
                    .HasColumnType("integer");

                b.Property<int>("maxMemorySpeedMhz")
                    .HasColumnType("integer");

                b.Property<int>("memoryChannels")
                    .HasColumnType("integer");

                b.Property<string>("memoryType")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("modelNumber")
                    .HasColumnType("text");

                b.Property<string>("name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int?>("pcieLanes")
                    .HasColumnType("integer");

                b.Property<string>("pcieVersion")
                    .HasColumnType("text");

                b.Property<decimal?>("priceUsd")
                    .HasColumnType("numeric");

                b.Property<string>("socket")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("tdpWatts")
                    .HasColumnType("integer");

                b.Property<int>("threads")
                    .HasColumnType("integer");

                b.HasKey("id");

                b.HasIndex("brandId");

                b.ToTable("cpu", null, t =>
                    {
                        t.ExcludeFromMigrations();
                    });
            });

        modelBuilder.Entity("PcBuilder.Models.CpuCooler", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                b.Property<int>("brandId")
                    .HasColumnType("integer");

                b.Property<string>("coolerType")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("fanCount")
                    .HasColumnType("integer");

                b.Property<int>("fanSizeMm")
                    .HasColumnType("integer");

                b.Property<bool>("hasRgb")
                    .HasColumnType("boolean");

                b.Property<int?>("heightMm")
                    .HasColumnType("integer");

                b.Property<int>("maxTdpWatts")
                    .HasColumnType("integer");

                b.Property<string>("name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<double?>("noiseLevelDb")
                    .HasColumnType("double precision");

                b.Property<decimal?>("priceUsd")
                    .HasColumnType("numeric");

                b.Property<int?>("radiatorSizeMm")
                    .HasColumnType("integer");

                b.PrimitiveCollection<string[]>("socketsSupported")
                    .IsRequired()
                    .HasColumnType("text[]");

                b.HasKey("id");

                b.HasIndex("brandId");

                b.ToTable("cpu_cooler", null, t =>
                    {
                        t.ExcludeFromMigrations();
                    });
            });

        modelBuilder.Entity("PcBuilder.Models.Gpu", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                b.Property<int?>("baseClockMhz")
                    .HasColumnType("integer");

                b.Property<int>("boostClockMhz")
                    .HasColumnType("integer");

                b.Property<int>("brandId")
                    .HasColumnType("integer");

                b.Property<int?>("cardLengthMm")
                    .HasColumnType("integer");

                b.Property<double>("cordSlots")
                    .HasColumnType("double precision");

                b.Property<string>("gpuChip")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("gpuInterface")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<bool>("hasRgb")
                    .HasColumnType("boolean");

                b.Property<double?>("memoryBandwithGb")
                    .HasColumnType("double precision");

                b.Property<int>("memoryBusBits")
                    .HasColumnType("integer");

                b.Property<string>("name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("outputDp")
                    .HasColumnType("integer");

                b.Property<int>("outputHdmi")
                    .HasColumnType("integer");

                b.Property<string>("powerConnectors")
                    .HasColumnType("text");

                b.Property<decimal?>("price")
                    .HasColumnType("numeric");

                b.Property<int>("recommendedPsuWattage")
                    .HasColumnType("integer");

                b.Property<int>("tdpWatts")
                    .HasColumnType("integer");

                b.Property<string>("vramType")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("vram_gb")
                    .HasColumnType("integer");

                b.HasKey("id");

                b.HasIndex("brandId");

                b.ToTable("gpu", null, t =>
                    {
                        t.ExcludeFromMigrations();
                    });
            });

        modelBuilder.Entity("PcBuilder.Models.HardDrive", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                b.Property<int>("brandId")
                    .HasColumnType("integer");

                b.Property<int?>("cacheMb")
                    .HasColumnType("integer");

                b.Property<int>("capacityGb")
                    .HasColumnType("integer");

                b.Property<string>("driveInterface")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("formFactor")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<bool>("isSsd")
                    .HasColumnType("boolean");

                b.Property<string>("name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<double?>("powerWatts")
                    .HasColumnType("double precision");

                b.Property<decimal?>("priceUsd")
                    .HasColumnType("numeric");

                b.Property<int?>("readSpeedMbS")
                    .HasColumnType("integer");

                b.Property<int?>("rpm")
                    .HasColumnType("integer");

                b.Property<int?>("tbw")
                    .HasColumnType("integer");

                b.Property<int?>("writeSpeedMbs")
                    .HasColumnType("integer");

                b.HasKey("id");

                b.HasIndex("brandId");

                b.ToTable("hard_drive", null, t =>
                    {
                        t.ExcludeFromMigrations();
                    });
            });

        modelBuilder.Entity("PcBuilder.Models.Motherboard", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                b.Property<int>("argbHeaders")
                    .HasColumnType("integer");

                b.Property<int>("brandId")
                    .HasColumnType("integer");

                b.Property<string>("chipset")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("fanHeaders")
                    .HasColumnType("integer");

                b.Property<bool>("hasBluetooth")
                    .HasColumnType("boolean");

                b.Property<bool>("hasWifi")
                    .HasColumnType("boolean");

                b.Property<int>("lanSpeedGbps")
                    .HasColumnType("integer");

                b.Property<int>("m2Slots")
                    .HasColumnType("integer");

                b.Property<int>("maxMemoryGb")
                    .HasColumnType("integer");

                b.Property<int>("maxMemorySpeedMhz")
                    .HasColumnType("integer");

                b.Property<int>("memorySlots")
                    .HasColumnType("integer");

                b.Property<string>("memoryType")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("pcieX16Slots")
                    .HasColumnType("integer");

                b.Property<int>("pcieX1Slots")
                    .HasColumnType("integer");

                b.Property<decimal?>("priceUsd")
                    .HasColumnType("numeric");

                b.Property<int>("rearDisplayPort")
                    .HasColumnType("integer");

                b.Property<int>("rearHdmi")
                    .HasColumnType("integer");

                b.Property<int>("rearUsbA")
                    .HasColumnType("integer");

                b.Property<int>("rearUsbC")
                    .HasColumnType("integer");

                b.Property<int>("sataPorts")
                    .HasColumnType("integer");

                b.Property<string>("socket")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("usbHeaders2Gen0")
                    .HasColumnType("integer");

                b.Property<int>("usbHeaders3Gen2")
                    .HasColumnType("integer");

                b.Property<int?>("vrmPhases")
                    .HasColumnType("integer");

                b.HasKey("id");

                b.HasIndex("brandId");

                b.ToTable("motherboard", null, t =>
                    {
                        t.ExcludeFromMigrations();
                    });
            });

        modelBuilder.Entity("PcBuilder.Models.PcMonitor", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                b.Property<int>("brandId")
                    .HasColumnType("integer");

                b.Property<int?>("brightnessNits")
                    .HasColumnType("integer");

                b.Property<int?>("colorGamutP3")
                    .HasColumnType("integer");

                b.Property<string>("contrastRatio")
                    .HasColumnType("text");

                b.Property<int>("dpPorts")
                    .HasColumnType("integer");

                b.Property<string>("dpVersion")
                    .HasColumnType("text");

                b.Property<bool>("hasFreeSync")
                    .HasColumnType("boolean");

                b.Property<bool>("hasFreeSyncPremium")
                    .HasColumnType("boolean");

                b.Property<bool>("hasGSync")
                    .HasColumnType("boolean");

                b.Property<bool>("hasSpeakers")
                    .HasColumnType("boolean");

                b.Property<bool>("hasUsbHub")
                    .HasColumnType("boolean");

                b.Property<int>("hdmiPorts")
                    .HasColumnType("integer");

                b.Property<string>("hdmiVersion")
                    .HasColumnType("text");

                b.Property<string>("hdrSupport")
                    .HasColumnType("text");

                b.Property<bool>("heightAdjustable")
                    .HasColumnType("boolean");

                b.Property<string>("name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("panelType")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<decimal?>("priceUsd")
                    .HasColumnType("numeric");

                b.Property<int>("refreshRateHz")
                    .HasColumnType("integer");

                b.Property<int>("resolutionHeight")
                    .HasColumnType("integer");

                b.Property<int>("resolutionWidth")
                    .HasColumnType("integer");

                b.Property<double?>("responseTimeMs")
                    .HasColumnType("double precision");

                b.Property<double>("screenSizeInch")
                    .HasColumnType("double precision");

                b.Property<int>("usbCPorts")
                    .HasColumnType("integer");

                b.Property<string>("vesaMount")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("id");

                b.HasIndex("brandId");

                b.ToTable("monitor", null, t =>
                    {
                        t.ExcludeFromMigrations();
                    });
            });

        modelBuilder.Entity("PcBuilder.Models.Psu", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                b.Property<string>("atxVersion")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("brandId")
                    .HasColumnType("integer");

                b.Property<string>("efficiency")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("epsConnectors")
                    .HasColumnType("integer");

                b.Property<int>("fanSizeMm")
                    .HasColumnType("integer");

                b.Property<bool>("has16Pin")
                    .HasColumnType("boolean");

                b.Property<int?>("lengthMm")
                    .HasColumnType("integer");

                b.Property<string>("modularity")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("pcie8PinConnectors")
                    .HasColumnType("integer");

                b.Property<decimal?>("priceUsd")
                    .HasColumnType("numeric");

                b.Property<int>("sataConnectors")
                    .HasColumnType("integer");

                b.Property<int>("wattage")
                    .HasColumnType("integer");

                b.HasKey("id");

                b.HasIndex("brandId");

                b.ToTable("psu", null, t =>
                    {
                        t.ExcludeFromMigrations();
                    });
            });

        modelBuilder.Entity("PcBuilder.Models.Ram", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                b.Property<int>("brandId")
                    .HasColumnType("integer");

                b.Property<int>("capacityGb")
                    .HasColumnType("integer");

                b.Property<int?>("casLatency")
                    .HasColumnType("integer");

                b.Property<bool>("hasEcc")
                    .HasColumnType("boolean");

                b.Property<bool>("hasRgb")
                    .HasColumnType("boolean");

                b.Property<int?>("heightMm")
                    .HasColumnType("integer");

                b.Property<int>("kitCount")
                    .HasColumnType("integer");

                b.Property<string>("memoryType")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("name")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<decimal?>("priceUsd")
                    .HasColumnType("numeric");

                b.Property<int>("speedMhz")
                    .HasColumnType("integer");

                b.Property<double?>("voltage")
                    .HasColumnType("double precision");

                b.HasKey("id");

                b.HasIndex("brandId");

                b.ToTable("memory", null, t =>
                    {
                        t.ExcludeFromMigrations();
                    });
            });

        modelBuilder.Entity("PcBuilder.Models.RegularUser", b =>
            {
                b.Property<int>("id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                b.Property<int>("buildsCreated")
                    .HasColumnType("integer");

                b.Property<string>("postalCode")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("prefferedCurrency")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("userId")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("id");

                b.HasIndex("userId");

                b.ToTable("regular_user");
            });

        modelBuilder.Entity("PcBuilder.Models.User", b =>
            {
                b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                b.HasDiscriminator().HasValue("User");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("PcBuilder.Models.Admin", b =>
            {
                b.HasOne("PcBuilder.Models.User", "user")
                    .WithMany()
                    .HasForeignKey("userId");

                b.Navigation("user");
            });

        modelBuilder.Entity("PcBuilder.Models.Build", b =>
            {
                b.HasOne("PcBuilder.Models.Case", "pcCase")
                    .WithMany()
                    .HasForeignKey("caseId");

                b.HasOne("PcBuilder.Models.CpuCooler", "cpuCooler")
                    .WithMany()
                    .HasForeignKey("cpuCoolerId");

                b.HasOne("PcBuilder.Models.Cpu", "cpu")
                    .WithMany()
                    .HasForeignKey("cpuId");

                b.HasOne("PcBuilder.Models.Gpu", "gpu")
                    .WithMany()
                    .HasForeignKey("gpuId");

                b.HasOne("PcBuilder.Models.HardDrive", "hardDrive")
                    .WithMany()
                    .HasForeignKey("hardDriveId");

                b.HasOne("PcBuilder.Models.PcMonitor", "monitor")
                    .WithMany()
                    .HasForeignKey("monitorId");

                b.HasOne("PcBuilder.Models.Motherboard", "motherboard")
                    .WithMany()
                    .HasForeignKey("motherboardId");

                b.HasOne("PcBuilder.Models.Psu", "psu")
                    .WithMany()
                    .HasForeignKey("psuId");

                b.HasOne("PcBuilder.Models.Ram", "ram")
                    .WithMany()
                    .HasForeignKey("ramId");

                b.HasOne("PcBuilder.Models.User", "user")
                    .WithMany()
                    .HasForeignKey("userId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.Navigation("cpu");

                b.Navigation("cpuCooler");

                b.Navigation("gpu");

                b.Navigation("hardDrive");

                b.Navigation("monitor");

                b.Navigation("motherboard");

                b.Navigation("pcCase");

                b.Navigation("psu");

                b.Navigation("ram");

                b.Navigation("user");
            });

        modelBuilder.Entity("PcBuilder.Models.Case", b =>
            {
                b.HasOne("PcBuilder.Models.Brand", "brand")
                    .WithMany()
                    .HasForeignKey("brandId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("brand");
            });

        modelBuilder.Entity("PcBuilder.Models.Cpu", b =>
            {
                b.HasOne("PcBuilder.Models.Brand", "brand")
                    .WithMany()
                    .HasForeignKey("brandId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("brand");
            });

        modelBuilder.Entity("PcBuilder.Models.CpuCooler", b =>
            {
                b.HasOne("PcBuilder.Models.Brand", "brand")
                    .WithMany()
                    .HasForeignKey("brandId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("brand");
            });

        modelBuilder.Entity("PcBuilder.Models.Gpu", b =>
            {
                b.HasOne("PcBuilder.Models.Brand", "brand")
                    .WithMany()
                    .HasForeignKey("brandId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("brand");
            });

        modelBuilder.Entity("PcBuilder.Models.HardDrive", b =>
            {
                b.HasOne("PcBuilder.Models.Brand", "brand")
                    .WithMany()
                    .HasForeignKey("brandId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("brand");
            });

        modelBuilder.Entity("PcBuilder.Models.Motherboard", b =>
            {
                b.HasOne("PcBuilder.Models.Brand", "brand")
                    .WithMany()
                    .HasForeignKey("brandId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("brand");
            });

        modelBuilder.Entity("PcBuilder.Models.PcMonitor", b =>
            {
                b.HasOne("PcBuilder.Models.Brand", "brand")
                    .WithMany()
                    .HasForeignKey("brandId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("brand");
            });

        modelBuilder.Entity("PcBuilder.Models.Psu", b =>
            {
                b.HasOne("PcBuilder.Models.Brand", "brand")
                    .WithMany()
                    .HasForeignKey("brandId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("brand");
            });

        modelBuilder.Entity("PcBuilder.Models.Ram", b =>
            {
                b.HasOne("PcBuilder.Models.Brand", "brand")
                    .WithMany()
                    .HasForeignKey("brandId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("brand");
            });

        modelBuilder.Entity("PcBuilder.Models.RegularUser", b =>
            {
                b.HasOne("PcBuilder.Models.User", "user")
                    .WithMany()
                    .HasForeignKey("userId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("user");
            });
#pragma warning restore 612, 618
    }
}
