// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PcBuilder.Data;
using PcBuilder.Enums;

#nullable disable

namespace PcBuilder.Migrations
{
    [DbContext(typeof(PcDbContext))]
    [Migration("20260513115530_ChangePsuModularEnumFieldName")]
    partial class ChangePsuModularEnumFieldName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "cooler_type", new[] { "AIO Liquid", "Air", "Custom Liquid" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "form_factor", new[] { "ATX", "E-ATX", "Micro-ATX", "Mini-ITX", "SSI-CEB", "XL-ATX" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "gpu_interface", new[] { "PCIe 3.0 x16", "PCIe 4.0 x16", "PCIe 5.0 x16" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "memory_type", new[] { "DDR4", "DDR4/DDR5", "DDR5" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "panel_type", new[] { "IPS", "Mini-LED", "OLED", "QD-OLED", "TN", "VA" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "psu_modular", new[] { "Fully-Modular", "Non-Modular", "Semi-Modular" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "psu_rating", new[] { "80+ Bronze", "80+ Gold", "80+ Platinum", "80+ Silver", "80+ Titanium", "80+ White" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "socket_type", new[] { "AM4", "AM5", "LGA1200", "LGA1700", "LGA1851", "LGA2066", "SP3", "sTR4", "sTRX4" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "storage_form_factor", new[] { "2.5", "3.5", "Add-In Card", "M.2 22110", "M.2 2242", "M.2 2260", "M.2 2280", "U.2" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "storage_interface", new[] { "NVMe PCIe 3.0", "NVMe PCIe 4.0", "NVMe PCIe 5.0", "SAS", "SATA III" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PcBuilder.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("PcBuilder.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Brand", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PcBuilder.Models.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CaseId")
                        .HasColumnType("integer");

                    b.Property<int?>("CpuCoolerId")
                        .HasColumnType("integer");

                    b.Property<int?>("CpuId")
                        .HasColumnType("integer");

                    b.Property<int?>("GpuId")
                        .HasColumnType("integer");

                    b.Property<int?>("HardDriveId")
                        .HasColumnType("integer");

                    b.Property<int?>("MonitorId")
                        .HasColumnType("integer");

                    b.Property<int?>("MotherboardId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("PsuId")
                        .HasColumnType("integer");

                    b.Property<int?>("RamId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("CpuCoolerId");

                    b.HasIndex("CpuId");

                    b.HasIndex("GpuId");

                    b.HasIndex("HardDriveId");

                    b.HasIndex("MonitorId");

                    b.HasIndex("MotherboardId");

                    b.HasIndex("PsuId");

                    b.HasIndex("RamId");

                    b.HasIndex("UserId");

                    b.ToTable("Build");
                });

            modelBuilder.Entity("PcBuilder.Models.Cpu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("BaseClockGhz")
                        .HasColumnType("double precision")
                        .HasColumnName("base_clock_ghz");

                    b.Property<double?>("BoostClockGhz")
                        .HasColumnType("double precision")
                        .HasColumnName("boost_clock_ghz");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.PrimitiveCollection<List<string>>("ChipsetsSupported")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("chipsets_supported");

                    b.Property<int>("Cores")
                        .HasColumnType("integer")
                        .HasColumnName("cores");

                    b.Property<string>("IgpuModel")
                        .HasColumnType("text")
                        .HasColumnName("igpu_model");

                    b.Property<bool>("IncludesCooler")
                        .HasColumnType("boolean")
                        .HasColumnName("includes_cooler");

                    b.Property<bool>("IntegratedGraphics")
                        .HasColumnType("boolean")
                        .HasColumnName("integrated_graphics");

                    b.Property<int?>("L3CacheMb")
                        .HasColumnType("integer")
                        .HasColumnName("l3_cache_mb");

                    b.Property<int?>("LaunchedYear")
                        .HasColumnType("integer")
                        .HasColumnName("launched_year");

                    b.Property<int>("MaxMemoryGb")
                        .HasColumnType("integer")
                        .HasColumnName("max_memory_gb");

                    b.Property<int>("MaxMemorySpeedMhz")
                        .HasColumnType("integer")
                        .HasColumnName("max_memory_speed_mhz");

                    b.Property<int>("MemoryChannels")
                        .HasColumnType("integer")
                        .HasColumnName("memory_channels");

                    b.Property<MemoryType>("MemoryType")
                        .HasColumnType("memory_type")
                        .HasColumnName("memory_type");

                    b.Property<string>("ModelNumber")
                        .HasColumnType("text")
                        .HasColumnName("model_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("PcieLanes")
                        .HasColumnType("integer")
                        .HasColumnName("pcie_lanes");

                    b.Property<string>("PcieVersion")
                        .HasColumnType("text")
                        .HasColumnName("pcie_version");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd");

                    b.Property<PcSocketType>("Socket")
                        .HasColumnType("socket_type")
                        .HasColumnName("socket");

                    b.Property<int>("TdpWatts")
                        .HasColumnType("integer")
                        .HasColumnName("tdp_watts");

                    b.Property<int>("Threads")
                        .HasColumnType("integer")
                        .HasColumnName("threads");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Cpu", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PcBuilder.Models.CpuCooler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<CoolerType>("CoolerType")
                        .HasColumnType("cooler_type")
                        .HasColumnName("cooler_type");

                    b.Property<int>("FanCount")
                        .HasColumnType("integer")
                        .HasColumnName("fan_count");

                    b.Property<int>("FanSizeMm")
                        .HasColumnType("integer")
                        .HasColumnName("fan_size_mm");

                    b.Property<bool>("HasRgb")
                        .HasColumnType("boolean")
                        .HasColumnName("has_rgb");

                    b.Property<int?>("HeightMm")
                        .HasColumnType("integer")
                        .HasColumnName("height_mm");

                    b.Property<int>("MaxTdpWatts")
                        .HasColumnType("integer")
                        .HasColumnName("max_tdp_watts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double?>("NoiseLevelDb")
                        .HasColumnType("double precision")
                        .HasColumnName("noise_db");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd");

                    b.Property<int?>("RadiatorSizeMm")
                        .HasColumnType("integer")
                        .HasColumnName("radiator_size_mm");

                    b.PrimitiveCollection<List<PcSocketType>>("SocketsSupported")
                        .IsRequired()
                        .HasColumnType("socket_type[]")
                        .HasColumnName("socket_support");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("CpuCooler", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PcBuilder.Models.Gpu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseClockMhz")
                        .HasColumnType("integer")
                        .HasColumnName("base_clock_mhz");

                    b.Property<int>("BoostClockMhz")
                        .HasColumnType("integer")
                        .HasColumnName("boost_clock_mhz");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<int?>("CardLengthMm")
                        .HasColumnType("integer")
                        .HasColumnName("card_length_mm");

                    b.Property<double>("CardSlots")
                        .HasColumnType("double precision")
                        .HasColumnName("card_slots");

                    b.Property<string>("GpuChip")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gpu_chip");

                    b.Property<GpuInterface>("GpuInterface")
                        .HasColumnType("gpu_interface")
                        .HasColumnName("interface");

                    b.Property<bool>("HasRgb")
                        .HasColumnType("boolean")
                        .HasColumnName("has_rgb");

                    b.Property<double?>("MemoryBandwithGb")
                        .HasColumnType("double precision")
                        .HasColumnName("memory_bandwidth_gbps");

                    b.Property<int>("MemoryBusBits")
                        .HasColumnType("integer")
                        .HasColumnName("memory_bus_bits");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OutputDp")
                        .HasColumnType("integer")
                        .HasColumnName("outputs_dp");

                    b.Property<int>("OutputHdmi")
                        .HasColumnType("integer")
                        .HasColumnName("outputs_hdmi");

                    b.Property<string>("PowerConnectors")
                        .HasColumnType("text")
                        .HasColumnName("power_connectors");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd");

                    b.Property<int>("RecommendedPsuWattage")
                        .HasColumnType("integer")
                        .HasColumnName("recommended_psu_w");

                    b.Property<int>("TdpWatts")
                        .HasColumnType("integer")
                        .HasColumnName("tdp_watts");

                    b.Property<int>("VramGb")
                        .HasColumnType("integer")
                        .HasColumnName("vram_gb");

                    b.Property<string>("VramType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vram_type");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Gpu", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PcBuilder.Models.HardDrive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<int?>("CacheMb")
                        .HasColumnType("integer")
                        .HasColumnName("cache_mb");

                    b.Property<int>("CapacityGb")
                        .HasColumnType("integer")
                        .HasColumnName("capacity_gb");

                    b.Property<StorageInterface>("DriveInterface")
                        .HasColumnType("storage_interface")
                        .HasColumnName("interface");

                    b.Property<StorageFormFactor>("FormFactor")
                        .HasColumnType("storage_form_factor")
                        .HasColumnName("form_factor");

                    b.Property<bool>("IsSsd")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ssd");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double?>("PowerWatts")
                        .HasColumnType("double precision")
                        .HasColumnName("power_watts");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd");

                    b.Property<int?>("ReadSpeedMbS")
                        .HasColumnType("integer")
                        .HasColumnName("read_speed_mbps");

                    b.Property<int?>("Rpm")
                        .HasColumnType("integer");

                    b.Property<int?>("Tbw")
                        .HasColumnType("integer");

                    b.Property<int?>("WriteSpeedMbs")
                        .HasColumnType("integer")
                        .HasColumnName("write_speed_mbps");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("HardDrive", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PcBuilder.Models.Motherboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArgbHeaders")
                        .HasColumnType("integer")
                        .HasColumnName("argb_headers");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<string>("Chipset")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chipset");

                    b.Property<int>("FanHeaders")
                        .HasColumnType("integer")
                        .HasColumnName("fan_headers");

                    b.Property<FormFactor>("FormFactor")
                        .HasColumnType("form_factor")
                        .HasColumnName("form_factor");

                    b.Property<bool>("HasBluetooth")
                        .HasColumnType("boolean")
                        .HasColumnName("has_bluetooth");

                    b.Property<bool>("HasWifi")
                        .HasColumnType("boolean")
                        .HasColumnName("has_wifi");

                    b.Property<int>("LanSpeedGbps")
                        .HasColumnType("integer")
                        .HasColumnName("lan_speed_gbps");

                    b.Property<int>("M2Slots")
                        .HasColumnType("integer")
                        .HasColumnName("m2_slots");

                    b.Property<int>("MaxMemoryGb")
                        .HasColumnType("integer")
                        .HasColumnName("max_memory_gb");

                    b.Property<int>("MaxMemorySpeedMhz")
                        .HasColumnType("integer")
                        .HasColumnName("max_memory_speed_mhz");

                    b.Property<int>("MemorySlots")
                        .HasColumnType("integer")
                        .HasColumnName("memory_slots");

                    b.Property<MemoryType>("MemoryType")
                        .HasColumnType("memory_type")
                        .HasColumnName("memory_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PcieX16Slots")
                        .HasColumnType("integer")
                        .HasColumnName("pcie_x16_slots");

                    b.Property<int>("PcieX1Slots")
                        .HasColumnType("integer")
                        .HasColumnName("pcie_x1_slots");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd");

                    b.Property<bool>("RearDisplayPort")
                        .HasColumnType("boolean")
                        .HasColumnName("rear_displayport");

                    b.Property<bool>("RearHdmi")
                        .HasColumnType("boolean")
                        .HasColumnName("rear_hdmi");

                    b.Property<int>("RearUsbA")
                        .HasColumnType("integer")
                        .HasColumnName("rear_usb_a");

                    b.Property<int>("RearUsbC")
                        .HasColumnType("integer")
                        .HasColumnName("rear_usb_c");

                    b.Property<int>("SataPorts")
                        .HasColumnType("integer")
                        .HasColumnName("sata_ports");

                    b.Property<PcSocketType>("Socket")
                        .HasColumnType("socket_type")
                        .HasColumnName("socket");

                    b.Property<int>("UsbHeaders2Gen0")
                        .HasColumnType("integer")
                        .HasColumnName("usb_headers_2_0");

                    b.Property<int>("UsbHeaders3Gen2")
                        .HasColumnType("integer")
                        .HasColumnName("usb_headers_3_2");

                    b.Property<int?>("VrmPhases")
                        .HasColumnType("integer")
                        .HasColumnName("vrm_phases");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Motherboard", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PcBuilder.Models.PcCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<int?>("CaseDepthMm")
                        .HasColumnType("integer")
                        .HasColumnName("case_depth_mm");

                    b.Property<int?>("CaseHeightMm")
                        .HasColumnType("integer")
                        .HasColumnName("case_height_mm");

                    b.Property<int?>("CaseWidthMm")
                        .HasColumnType("integer")
                        .HasColumnName("case_width_mm");

                    b.Property<int>("DriveBays25Inch")
                        .HasColumnType("integer")
                        .HasColumnName("drive_bays_25");

                    b.Property<int>("DriveBays35Inch")
                        .HasColumnType("integer")
                        .HasColumnName("drive_bays_35");

                    b.Property<int>("FrontUsbA")
                        .HasColumnType("integer")
                        .HasColumnName("front_usb_a");

                    b.Property<int>("FrontUsbC")
                        .HasColumnType("integer")
                        .HasColumnName("front_usb_c");

                    b.Property<bool>("HasGlassPanel")
                        .HasColumnType("boolean")
                        .HasColumnName("has_glass_panel");

                    b.Property<int>("IncludedFans")
                        .HasColumnType("integer")
                        .HasColumnName("included_fans");

                    b.Property<int>("MaxCpuCoolerHeightMm")
                        .HasColumnType("integer")
                        .HasColumnName("max_cpu_cooler_height_mm");

                    b.Property<int>("MaxGpuLengthMm")
                        .HasColumnType("integer")
                        .HasColumnName("max_gpu_length_mm");

                    b.Property<int>("MaxPsuLengthMm")
                        .HasColumnType("integer")
                        .HasColumnName("max_psu_length_mm");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd");

                    b.PrimitiveCollection<List<int>>("RadiatorSupportMm")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("radiator_support_mm");

                    b.PrimitiveCollection<List<FormFactor>>("SupportedFormFactors")
                        .IsRequired()
                        .HasColumnType("form_factor[]")
                        .HasColumnName("form_factors_supported");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("PcCase", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PcBuilder.Models.PcMonitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<int?>("BrightnessNits")
                        .HasColumnType("integer")
                        .HasColumnName("brightness_nits");

                    b.Property<int?>("ColorGamutP3")
                        .HasColumnType("integer")
                        .HasColumnName("color_gamut_p3");

                    b.Property<string>("ContrastRatio")
                        .HasColumnType("text")
                        .HasColumnName("contrast_ratio");

                    b.Property<int>("DpPorts")
                        .HasColumnType("integer")
                        .HasColumnName("inputs_dp");

                    b.Property<string>("DpVersion")
                        .HasColumnType("text")
                        .HasColumnName("dp_version");

                    b.Property<bool>("HasFreeSync")
                        .HasColumnType("boolean")
                        .HasColumnName("has_freesync");

                    b.Property<bool>("HasFreeSyncPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("has_freesync_premium");

                    b.Property<bool>("HasGSync")
                        .HasColumnType("boolean")
                        .HasColumnName("has_gsync");

                    b.Property<bool>("HasSpeakers")
                        .HasColumnType("boolean")
                        .HasColumnName("has_speakers");

                    b.Property<bool>("HasUsbHub")
                        .HasColumnType("boolean")
                        .HasColumnName("has_usb_hub");

                    b.Property<int>("HdmiPorts")
                        .HasColumnType("integer")
                        .HasColumnName("inputs_hdmi");

                    b.Property<string>("HdmiVersion")
                        .HasColumnType("text")
                        .HasColumnName("hdmi_version");

                    b.Property<string>("HdrSupport")
                        .HasColumnType("text")
                        .HasColumnName("hdr_support");

                    b.Property<bool>("HeightAdjustable")
                        .HasColumnType("boolean")
                        .HasColumnName("height_adjustable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<PanelType>("PanelType")
                        .HasColumnType("panel_type")
                        .HasColumnName("panel_type");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd");

                    b.Property<int>("RefreshRateHz")
                        .HasColumnType("integer")
                        .HasColumnName("refresh_rate_hz");

                    b.Property<int>("ResolutionHeight")
                        .HasColumnType("integer")
                        .HasColumnName("resolution_height");

                    b.Property<int>("ResolutionWidth")
                        .HasColumnType("integer")
                        .HasColumnName("resolution_width");

                    b.Property<double?>("ResponseTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("response_time_ms");

                    b.Property<double>("ScreenSizeInch")
                        .HasColumnType("double precision")
                        .HasColumnName("screen_size_inch");

                    b.Property<int>("UsbCPorts")
                        .HasColumnType("integer")
                        .HasColumnName("inputs_usb_c");

                    b.Property<string>("VesaMount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vesa_mount");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("PcMonitor", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PcBuilder.Models.Psu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AtxVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("atx_version");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<PsuRating>("Efficiency")
                        .HasColumnType("psu_rating")
                        .HasColumnName("efficiency");

                    b.Property<int>("EpsConnectors")
                        .HasColumnType("integer")
                        .HasColumnName("eps_connectors");

                    b.Property<int>("FanSizeMm")
                        .HasColumnType("integer")
                        .HasColumnName("fan_size_mm");

                    b.Property<bool>("Has16Pin")
                        .HasColumnType("boolean")
                        .HasColumnName("has_16pin");

                    b.Property<int?>("LengthMm")
                        .HasColumnType("integer")
                        .HasColumnName("length_mm");

                    b.Property<PsuModular>("Modularity")
                        .HasColumnType("psu_modular")
                        .HasColumnName("modular");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Pcie8PinConnectors")
                        .HasColumnType("integer")
                        .HasColumnName("pcie_8pin");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd");

                    b.Property<int>("SataConnectors")
                        .HasColumnType("integer")
                        .HasColumnName("sata_connectors");

                    b.Property<int>("Wattage")
                        .HasColumnType("integer")
                        .HasColumnName("wattage");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Psu", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PcBuilder.Models.Ram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<int>("CapacityGb")
                        .HasColumnType("integer")
                        .HasColumnName("capacity_gb");

                    b.Property<int?>("CasLatency")
                        .HasColumnType("integer")
                        .HasColumnName("cas_latency");

                    b.Property<bool>("HasEcc")
                        .HasColumnType("boolean")
                        .HasColumnName("has_ecc");

                    b.Property<bool>("HasRgb")
                        .HasColumnType("boolean")
                        .HasColumnName("has_rgb");

                    b.Property<int?>("HeightMm")
                        .HasColumnType("integer")
                        .HasColumnName("height_mm");

                    b.Property<int>("KitCount")
                        .HasColumnType("integer")
                        .HasColumnName("kit_count");

                    b.Property<MemoryType>("MemoryType")
                        .HasColumnType("memory_type")
                        .HasColumnName("memory_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("price_usd");

                    b.Property<int>("SpeedMhz")
                        .HasColumnType("integer")
                        .HasColumnName("speed_mhz");

                    b.Property<double?>("Voltage")
                        .HasColumnType("double precision")
                        .HasColumnName("voltage");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Ram", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PcBuilder.Models.RegularUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildsCreated")
                        .HasColumnType("integer");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrefferedCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RegularUser");
                });

            modelBuilder.Entity("PcBuilder.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PcBuilder.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PcBuilder.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PcBuilder.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PcBuilder.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilder.Models.Admin", b =>
                {
                    b.HasOne("PcBuilder.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PcBuilder.Models.Build", b =>
                {
                    b.HasOne("PcBuilder.Models.PcCase", "PcCase")
                        .WithMany()
                        .HasForeignKey("CaseId");

                    b.HasOne("PcBuilder.Models.CpuCooler", "CpuCooler")
                        .WithMany()
                        .HasForeignKey("CpuCoolerId");

                    b.HasOne("PcBuilder.Models.Cpu", "Cpu")
                        .WithMany()
                        .HasForeignKey("CpuId");

                    b.HasOne("PcBuilder.Models.Gpu", "Gpu")
                        .WithMany()
                        .HasForeignKey("GpuId");

                    b.HasOne("PcBuilder.Models.HardDrive", "HardDrive")
                        .WithMany()
                        .HasForeignKey("HardDriveId");

                    b.HasOne("PcBuilder.Models.PcMonitor", "Monitor")
                        .WithMany()
                        .HasForeignKey("MonitorId");

                    b.HasOne("PcBuilder.Models.Motherboard", "Motherboard")
                        .WithMany()
                        .HasForeignKey("MotherboardId");

                    b.HasOne("PcBuilder.Models.Psu", "Psu")
                        .WithMany()
                        .HasForeignKey("PsuId");

                    b.HasOne("PcBuilder.Models.Ram", "Ram")
                        .WithMany()
                        .HasForeignKey("RamId");

                    b.HasOne("PcBuilder.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Cpu");

                    b.Navigation("CpuCooler");

                    b.Navigation("Gpu");

                    b.Navigation("HardDrive");

                    b.Navigation("Monitor");

                    b.Navigation("Motherboard");

                    b.Navigation("PcCase");

                    b.Navigation("Psu");

                    b.Navigation("Ram");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PcBuilder.Models.Cpu", b =>
                {
                    b.HasOne("PcBuilder.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PcBuilder.Models.CpuCooler", b =>
                {
                    b.HasOne("PcBuilder.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PcBuilder.Models.Gpu", b =>
                {
                    b.HasOne("PcBuilder.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PcBuilder.Models.HardDrive", b =>
                {
                    b.HasOne("PcBuilder.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PcBuilder.Models.Motherboard", b =>
                {
                    b.HasOne("PcBuilder.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PcBuilder.Models.PcCase", b =>
                {
                    b.HasOne("PcBuilder.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PcBuilder.Models.PcMonitor", b =>
                {
                    b.HasOne("PcBuilder.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PcBuilder.Models.Psu", b =>
                {
                    b.HasOne("PcBuilder.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PcBuilder.Models.Ram", b =>
                {
                    b.HasOne("PcBuilder.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PcBuilder.Models.RegularUser", b =>
                {
                    b.HasOne("PcBuilder.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
