// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PcBuilder.Data;

#nullable disable

namespace PcBuilder.Migrations
{
    [DbContext(typeof(PcDbContext))]
    partial class PcDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdminEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PcBuilder.Entities.BrandEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("PcBuilder.Entities.BuildEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CaseId")
                        .HasColumnType("integer");

                    b.Property<int?>("CpuCoolerId")
                        .HasColumnType("integer");

                    b.Property<int?>("CpuId")
                        .HasColumnType("integer");

                    b.Property<int?>("GpuId")
                        .HasColumnType("integer");

                    b.Property<int?>("HardDriveId")
                        .HasColumnType("integer");

                    b.Property<int?>("MonitorId")
                        .HasColumnType("integer");

                    b.Property<int?>("MotherboardId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("PsuId")
                        .HasColumnType("integer");

                    b.Property<int?>("RamId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("CpuCoolerId");

                    b.HasIndex("CpuId");

                    b.HasIndex("GpuId");

                    b.HasIndex("HardDriveId");

                    b.HasIndex("MonitorId");

                    b.HasIndex("MotherboardId");

                    b.HasIndex("PsuId");

                    b.HasIndex("RamId");

                    b.HasIndex("UserId");

                    b.ToTable("Build");
                });

            modelBuilder.Entity("PcBuilder.Entities.CpuCoolerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<string>("CoolerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FanCount")
                        .HasColumnType("integer");

                    b.Property<int>("FanSizeMm")
                        .HasColumnType("integer");

                    b.Property<bool>("HasRgb")
                        .HasColumnType("boolean");

                    b.Property<int?>("HeightMm")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTdpWatts")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("NoiseLevelDb")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("numeric");

                    b.Property<int?>("RadiatorSizeMm")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("SocketsSupported")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("CpuCooler");
                });

            modelBuilder.Entity("PcBuilder.Entities.CpuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("BaseClockGhz")
                        .HasColumnType("double precision");

                    b.Property<double?>("BoostClockGhz")
                        .HasColumnType("double precision");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("ChipsetsSupported")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Cores")
                        .HasColumnType("integer");

                    b.Property<string>("IgpuModel")
                        .HasColumnType("text");

                    b.Property<bool>("IncludesCooler")
                        .HasColumnType("boolean");

                    b.Property<bool>("IntegratedGraphics")
                        .HasColumnType("boolean");

                    b.Property<int?>("L3CacheMb")
                        .HasColumnType("integer");

                    b.Property<int?>("LaunchedYear")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMemoryGb")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMemorySpeedMhz")
                        .HasColumnType("integer");

                    b.Property<int>("MemoryChannels")
                        .HasColumnType("integer");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelNumber")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PcieLanes")
                        .HasColumnType("integer");

                    b.Property<string>("PcieVersion")
                        .HasColumnType("text");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TdpWatts")
                        .HasColumnType("integer");

                    b.Property<int>("Threads")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Cpu");
                });

            modelBuilder.Entity("PcBuilder.Entities.GpuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseClockMhz")
                        .HasColumnType("integer");

                    b.Property<int>("BoostClockMhz")
                        .HasColumnType("integer");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<int?>("CardLengthMm")
                        .HasColumnType("integer");

                    b.Property<double>("CardSlots")
                        .HasColumnType("double precision");

                    b.Property<string>("GpuChip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GpuInterface")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasRgb")
                        .HasColumnType("boolean");

                    b.Property<double?>("MemoryBandwithGb")
                        .HasColumnType("double precision");

                    b.Property<int>("MemoryBusBits")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OutputDp")
                        .HasColumnType("integer");

                    b.Property<int>("OutputHdmi")
                        .HasColumnType("integer");

                    b.Property<string>("PowerConnectors")
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("RecommendedPsuWattage")
                        .HasColumnType("integer");

                    b.Property<int>("TdpWatts")
                        .HasColumnType("integer");

                    b.Property<int>("VramGb")
                        .HasColumnType("integer");

                    b.Property<string>("VramType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Gpu");
                });

            modelBuilder.Entity("PcBuilder.Entities.HardDriveEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<int?>("CacheMb")
                        .HasColumnType("integer");

                    b.Property<int>("CapacityGb")
                        .HasColumnType("integer");

                    b.Property<string>("DriveInterface")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSsd")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("PowerWatts")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("numeric");

                    b.Property<int?>("ReadSpeedMbS")
                        .HasColumnType("integer");

                    b.Property<int?>("Rpm")
                        .HasColumnType("integer");

                    b.Property<int?>("Tbw")
                        .HasColumnType("integer");

                    b.Property<int?>("WriteSpeedMbs")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("HardDrive");
                });

            modelBuilder.Entity("PcBuilder.Entities.MotherboardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArgbHeaders")
                        .HasColumnType("integer");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<string>("Chipset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FanHeaders")
                        .HasColumnType("integer");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasBluetooth")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasWifi")
                        .HasColumnType("boolean");

                    b.Property<int>("LanSpeedGbps")
                        .HasColumnType("integer");

                    b.Property<int>("M2Slots")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMemoryGb")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMemorySpeedMhz")
                        .HasColumnType("integer");

                    b.Property<int>("MemorySlots")
                        .HasColumnType("integer");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PcieX16Slots")
                        .HasColumnType("integer");

                    b.Property<int>("PcieX1Slots")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("numeric");

                    b.Property<bool>("RearDisplayPort")
                        .HasColumnType("boolean");

                    b.Property<bool>("RearHdmi")
                        .HasColumnType("boolean");

                    b.Property<int>("RearUsbA")
                        .HasColumnType("integer");

                    b.Property<int>("RearUsbC")
                        .HasColumnType("integer");

                    b.Property<int>("SataPorts")
                        .HasColumnType("integer");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsbHeaders2Gen0")
                        .HasColumnType("integer");

                    b.Property<int>("UsbHeaders3Gen2")
                        .HasColumnType("integer");

                    b.Property<int?>("VrmPhases")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Motherboard");
                });

            modelBuilder.Entity("PcBuilder.Entities.PcCaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<int?>("CaseDepthMm")
                        .HasColumnType("integer");

                    b.Property<int?>("CaseHeightMm")
                        .HasColumnType("integer");

                    b.Property<int?>("CaseWidthMm")
                        .HasColumnType("integer");

                    b.Property<int>("DriveBays25Inch")
                        .HasColumnType("integer");

                    b.Property<int>("DriveBays35Inch")
                        .HasColumnType("integer");

                    b.Property<int>("FrontUsbA")
                        .HasColumnType("integer");

                    b.Property<int>("FrontUsbC")
                        .HasColumnType("integer");

                    b.Property<bool>("HasGlassPanel")
                        .HasColumnType("boolean");

                    b.Property<int>("IncludedFans")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCpuCoolerHeightMm")
                        .HasColumnType("integer");

                    b.Property<int>("MaxGpuLengthMm")
                        .HasColumnType("integer");

                    b.Property<int>("MaxPsuLengthMm")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("numeric");

                    b.PrimitiveCollection<List<string>>("RadiatorSupportMm")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<int[]>("SupportedFormFactors")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("PcCase");
                });

            modelBuilder.Entity("PcBuilder.Entities.PcMonitorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<int?>("BrightnessNits")
                        .HasColumnType("integer");

                    b.Property<int?>("ColorGamutP3")
                        .HasColumnType("integer");

                    b.Property<string>("ContrastRatio")
                        .HasColumnType("text");

                    b.Property<int>("DpPorts")
                        .HasColumnType("integer");

                    b.Property<string>("DpVersion")
                        .HasColumnType("text");

                    b.Property<bool>("HasFreeSync")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasFreeSyncPremium")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasGSync")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSpeakers")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasUsbHub")
                        .HasColumnType("boolean");

                    b.Property<int>("HdmiPorts")
                        .HasColumnType("integer");

                    b.Property<string>("HdmiVersion")
                        .HasColumnType("text");

                    b.Property<string>("HdrSupport")
                        .HasColumnType("text");

                    b.Property<bool>("HeightAdjustable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PanelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("numeric");

                    b.Property<int>("RefreshRateHz")
                        .HasColumnType("integer");

                    b.Property<int>("ResolutionHeight")
                        .HasColumnType("integer");

                    b.Property<int>("ResolutionWidth")
                        .HasColumnType("integer");

                    b.Property<double?>("ResponseTimeMs")
                        .HasColumnType("double precision");

                    b.Property<double>("ScreenSizeInch")
                        .HasColumnType("double precision");

                    b.Property<int>("UsbCPorts")
                        .HasColumnType("integer");

                    b.Property<string>("VesaMount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("PcMonitor");
                });

            modelBuilder.Entity("PcBuilder.Entities.PsuEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AtxVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<string>("Efficiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EpsConnectors")
                        .HasColumnType("integer");

                    b.Property<int>("FanSizeMm")
                        .HasColumnType("integer");

                    b.Property<bool>("Has16Pin")
                        .HasColumnType("boolean");

                    b.Property<int?>("LengthMm")
                        .HasColumnType("integer");

                    b.Property<string>("Modularity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Pcie8PinConnectors")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("numeric");

                    b.Property<int>("SataConnectors")
                        .HasColumnType("integer");

                    b.Property<int>("Wattage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Psu");
                });

            modelBuilder.Entity("PcBuilder.Entities.RamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<int>("CapacityGb")
                        .HasColumnType("integer");

                    b.Property<int?>("CasLatency")
                        .HasColumnType("integer");

                    b.Property<bool>("HasEcc")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasRgb")
                        .HasColumnType("boolean");

                    b.Property<int?>("HeightMm")
                        .HasColumnType("integer");

                    b.Property<int>("KitCount")
                        .HasColumnType("integer");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PriceUsd")
                        .HasColumnType("numeric");

                    b.Property<int>("SpeedMhz")
                        .HasColumnType("integer");

                    b.Property<double?>("Voltage")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Ram");
                });

            modelBuilder.Entity("PcBuilder.Entities.RegularUserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildsCreated")
                        .HasColumnType("integer");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrefferedCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RegularUser");
                });

            modelBuilder.Entity("PcBuilder.Entities.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AdminEntity", b =>
                {
                    b.HasOne("PcBuilder.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PcBuilder.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PcBuilder.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PcBuilder.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PcBuilder.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilder.Entities.BuildEntity", b =>
                {
                    b.HasOne("PcBuilder.Entities.PcCaseEntity", "PcCase")
                        .WithMany()
                        .HasForeignKey("CaseId");

                    b.HasOne("PcBuilder.Entities.CpuCoolerEntity", "CpuCooler")
                        .WithMany()
                        .HasForeignKey("CpuCoolerId");

                    b.HasOne("PcBuilder.Entities.CpuEntity", "Cpu")
                        .WithMany()
                        .HasForeignKey("CpuId");

                    b.HasOne("PcBuilder.Entities.GpuEntity", "Gpu")
                        .WithMany()
                        .HasForeignKey("GpuId");

                    b.HasOne("PcBuilder.Entities.HardDriveEntity", "HardDrive")
                        .WithMany()
                        .HasForeignKey("HardDriveId");

                    b.HasOne("PcBuilder.Entities.PcMonitorEntity", "Monitor")
                        .WithMany()
                        .HasForeignKey("MonitorId");

                    b.HasOne("PcBuilder.Entities.MotherboardEntity", "Motherboard")
                        .WithMany()
                        .HasForeignKey("MotherboardId");

                    b.HasOne("PcBuilder.Entities.PsuEntity", "Psu")
                        .WithMany()
                        .HasForeignKey("PsuId");

                    b.HasOne("PcBuilder.Entities.RamEntity", "Ram")
                        .WithMany()
                        .HasForeignKey("RamId");

                    b.HasOne("PcBuilder.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Cpu");

                    b.Navigation("CpuCooler");

                    b.Navigation("Gpu");

                    b.Navigation("HardDrive");

                    b.Navigation("Monitor");

                    b.Navigation("Motherboard");

                    b.Navigation("PcCase");

                    b.Navigation("Psu");

                    b.Navigation("Ram");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PcBuilder.Entities.CpuCoolerEntity", b =>
                {
                    b.HasOne("PcBuilder.Entities.BrandEntity", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PcBuilder.Entities.CpuEntity", b =>
                {
                    b.HasOne("PcBuilder.Entities.BrandEntity", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PcBuilder.Entities.GpuEntity", b =>
                {
                    b.HasOne("PcBuilder.Entities.BrandEntity", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PcBuilder.Entities.HardDriveEntity", b =>
                {
                    b.HasOne("PcBuilder.Entities.BrandEntity", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PcBuilder.Entities.MotherboardEntity", b =>
                {
                    b.HasOne("PcBuilder.Entities.BrandEntity", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PcBuilder.Entities.PcCaseEntity", b =>
                {
                    b.HasOne("PcBuilder.Entities.BrandEntity", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PcBuilder.Entities.PcMonitorEntity", b =>
                {
                    b.HasOne("PcBuilder.Entities.BrandEntity", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PcBuilder.Entities.PsuEntity", b =>
                {
                    b.HasOne("PcBuilder.Entities.BrandEntity", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PcBuilder.Entities.RamEntity", b =>
                {
                    b.HasOne("PcBuilder.Entities.BrandEntity", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("PcBuilder.Entities.RegularUserEntity", b =>
                {
                    b.HasOne("PcBuilder.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
